services:
  web:
    image: ghcr.io/andersthomsen92/devopscalculator:staging
    ports:
      - "8080:8080"   
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__CalculatorDb: Server=mariadb;Database=${DATABASE_NAME};User=${DATABASE_USER};Password=${DATABASE_PASSWORD};
      
      
  frontend:
    image: ghcr.io/andersthomsen92/devopscalculator-frontend:staging
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./clean-nginx.conf:/etc/nginx/nginx.conf   
  
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql

        
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - mariadb
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/${DATABASE_NAME}  #Does this also work as a connectionstring?
      FLYWAY_USER: ${DATABASE_USER}
      FLYWAY_PASSWORD: ${DATABASE_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./db/migrations:/flyway/sql
    command: migrate

volumes:
  mariadb_data:         