services:
  web:
    image: ghcr.io/andersthomsen92/devopscalculator:staging
    ports:
      - "8080:8080"   
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__CalculatorDb: Server=mariadb;Database=${DATABASE_NAME};User=${DATABASE_USER};Password=${DATABASE_PASSWORD};
    env_file:
      - .env
      
      
  frontend:
    image: ghcr.io/andersthomsen92/devopscalculator-frontend:staging
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf   
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
  
  flyway:
    image: flyway/flyway:latest
    depends_on:
      - mariadb
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./db/migrations:/flyway/sql
    command: migrate

volumes:

volumes:
  mariadb_data:         