services:
  web:
    image: ghcr.io/andersthomsen92/devopscalculator:staging
    ports:
      - "8080:8080"   
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__CalculatorDb: Server=mariadb;Database=${DATABASE_NAME};User=${DATABASE_USER};Password=${DATABASE_PASSWORD};
    depends_on:
      mariadb:
        condition: service_healthy  
      
      
  frontend:
    image: ghcr.io/andersthomsen92/devopscalculator-frontend:staging
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf   
  
  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      DATABASE_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s  

        
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - mariadb
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/${DATABASE_NAME}  #Does this also work as a connectionstring?
      FLYWAY_USER: ${DATABASE_USER}
      FLYWAY_PASSWORD: ${DATABASE_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./db/migrations:/flyway/sql
    command: migrate

volumes:
  mariadb_data:         