services:
  web:
    image: ghcr.io/andersthomsen92/devopscalculator:staging
    ports:
      - "8080:8080"   
  
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
        
  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    depends_on:
      - mariadb
    volumes:
      - ./db/migrations:/flyway/sql
    command:
      - "migrate"
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/mydatabase
      FLYWAY_USER: myuser
      FLYWAY_PASSWORD: mypassword
           