services:
  web:
    image: ghcr.io/andersthomsen92/devopscalculator:staging
    ports:
      - "8080:8080"   
    depends_on:
      - mariadb
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__CalculatorDb: Server=mariadb;Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};
      
      
  frontend:
    image: ghcr.io/andersthomsen92/devopscalculator-frontend:staging
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf   
  
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypass
      command: --bind-address=0.0.0.0
    volumes:
      - mariadb_data:/var/lib/mysql
  
  flyway:
    image: flyway/flyway:latest
    depends_on:
      - mariadb
    environment:
      FLYWAY_URL: jdbc:mariadb://mariadb:3306/${MYSQL_DATABASE}
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_CONNECT_RETRIES: 5
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
    volumes:
      - ./db/migrations:/flyway/sql
    command: migrate

volumes:
  mariadb_data: