name: workflow.yml
on:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for accurate results of code analysis

      - name: Install required tools
        run: |  # Install ReportGenerator and Stryker tools
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g dotnet-stryker

      - name: Run unit tests
        run: |
          dotnet test --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Debug: List files in TestResults
        run: |
          ls -R ./TestResults

      - name: Generate report
        run: |
          # This should look inside TestResults/{guid}/ for coverage.cobertura.xml
          reportgenerator -reports:"./TestResults/*/coverage.cobertura.xml" -targetdir:"Tests/CoverageOutput" -reporttypes:Html

      - name: Run Mutation Tests
        run: |
          dotnet stryker --break-at 80

      - name: Collect Coverage Report
        if: always
        uses: actions/upload-artifact@v3  # Upload the coverage report artifact to GitHub Actions
        with:
          name: coverage-report
          path: Tests/CoverageOutput/

      - name: Collect Stryker Report
        if: always
        uses: actions/upload-artifact@v3  # Upload the Stryker report artifact to GitHub Actions
        with:
          name: stryker-report
          path: ./Tests/StrykerOutput/
